### ISSUE TITLE
Final Code Submission Checklist

### ISSUE THREAD

**Issue by ngmor** [ngmor/attack-of-the-franka#13]
- [x] README for whole project (see [3.](https://nu-msr.github.io/ros_notes/ros2/final_project.html) for guidelines)
- [x] Update README for MoveIt API (see [3.](https://nu-msr.github.io/ros_notes/ros2/final_project.html) for guidelines)
- [x] README for `attack_of_the_franka` package (see [3.](https://nu-msr.github.io/ros_notes/ros2/final_project.html) for guidelines)
- [x] Unit test(s)
- [x] Integration test(s)
- [x] Flake8 standards
- [x] Make sure everything has a docstring (including top of nodes)
- [x] Make sure all tests pass
- [ ] Setup Sphinx
- [x] Take or select a video as the main video for our README
- [x] Merge to main
- [x] Retest everything

**Comment by megsindelar** [comment]
Add retest project to the list to make sure everything still runs

**Comment by ngmor** [comment]
You can add to the list with a comment! use `- [ ]` before the item you want to add (you can edit your comment above)

**Comment by ngmor** [comment]
- [ ] make sure the package xml and setup.py are updated with proper information.

**Comment by megsindelar** [comment]
- [  ] delete any pycaches
